services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - mysql # wartet darauf, dass MySQL bereit ist

  prefect:
    build: . # Dockerfile im aktuellen Verzeichnis wird verwendet
    container_name: prefect
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ./flows:/opt/prefect/flows # hier liegen deine Python-Flows
      - ./data:/opt/prefect/data # hier liegen CSV/Excel/JSON
    working_dir: /opt/prefect/flows
    environment:
      PREFECT_LOGGING_LEVEL: INFO
    depends_on:
      - mysql # nur nötig, wenn dein Flow auf MySQL zugreift
